[package]
name = "mvm"
version = "0.0.1"
edition = "2024"
description = "Multi-tenant Firecracker microVM fleet manager"

[lib]
name = "mvm"
path = "src/lib.rs"

[[bin]]
name = "mvm"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
colored = "3"
indicatif = "0.17"
inquire = "0.7"
quinn = "0.11"
rcgen = { version = "0.13", features = ["pem"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
rustls = { version = "0.23", features = ["ring"] }
rustls-pemfile = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
tera = "1"
uuid = { version = "1", features = ["v4"] }
which = "7"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
